language: python
services:
  - docker
python:
  - "2.7"

install:
  - make deps
  - make lint
script:
- make test

after_success:
  - make docker_build
  - make docker_push

deploy:
  provider: heroku
  app: se_hello_printer_app
  api_key:  ${HEROKU_API_KEY}
